axis_linear: 1 # Left thumb stick vertical
scale_linear: 2
scale_linear_turbo: 5

axis_angular: 0 # Left thumb stick horizontal
scale_angular: 2

enable_button: 7 # A button
enable_turbo_button: 6 # Right trigger button
