obstacle_range: 4.2
raytrace_range: 5.5
footprint: [[0.155, 0.155], [0.155, -0.155], [-0.155, -0.155], [-0.155, 0.155]]
#footprint_padding: 0.05
#footprint_inflation: 0.01
#robot_radius: 0.3
inflation_radius: 0.3
cost_scaling_factor: 9.0
map_type: costmap
#transform_tolerance: 1
observation_sources: scan
scan: { data_type: LaserScan, topic: /scan, marking: true, clearing: true }
