# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
# move_base软件包的通用配置参数,现在依次解释每个参数意义:

#   shutdown_costmaps:当move_base在不活动状态时,是否关掉costmap.

#   controller_frequency:向底盘控制移动话题cmd_vel发送命令的频率.

#   controller_patience:在空间清理操作执行前,控制器花多长时间等有效控制下发.

#   planner_frequency:全局规划操作的执行频率.如果设置为0.0,则全局规划器仅

#   在接收到新的目标点或者局部规划器报告路径堵塞时才会重新执行规划操作.

#   planner_patience:在空间清理操作执行前,留给规划器多长时间来找出一条有效规划.

#   oscillation_timeout:执行修复机制前,允许振荡的时长.

#   oscillation_distance:来回运动在多大距离以上不会被认为是振荡.

#   base_local_planner:指定用于move_base的局部规划器插件名称.

#   base_global_planner:指定用于move_base的全局规划器插件名称.


# shutdown_costmaps: false

# controller_frequency: 5.0
# controller_patience: 3.0


# planner_frequency: 1.0
# planner_patience: 5.0

# oscillation_timeout: 10.0
# oscillation_distance: 0.2
shutdown_costmaps: false

controller_frequency: 20.0 #10
controller_patience: 15 #3

conservative_reset_dist: 0.0 ##add
planner_frequency: 20.0 #10.0
planner_patience: 5.0  #15 #25在空间清理操作执行前，路径规划器等待多长时间（秒）用来找出一个有效规划。


oscillation_timeout: 10.0
oscillation_distance: 0.2

clearing_rotation_allowed: false

# local planner - default is trajectory rollout
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

base_global_planner: "astar_planner/AstarPlanner"  
#alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner,astar_planner/AstarPlanner


#We plan to integrate recovery behaviors for turtlebot but currently those belong to gopher and still have to be adapted.
## recovery behaviors; we avoid spinning, but we need a fall-back replanning
#recovery_behavior_enabled: true

#recovery_behaviors:
  #- name: 'super_conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation1'
    #type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
    #type: 'rotate_recovery/RotateRecovery'

#super_conservative_reset1:
  #reset_distance: 3.0
#conservative_reset1:
  #reset_distance: 1.5
#aggressive_reset1:
  #reset_distance: 0.0
#super_conservative_reset2:
  #reset_distance: 3.0
#conservative_reset2:
  #reset_distance: 1.5
#aggressive_reset2:
  #reset_distance: 0.0
